expedientes/urls.py
from django.contrib.auth.views import LoginView

from django.urls import path
from django.conf.urls import url

from .views import (
    vistaExpediente,
    vistaApp,
    vistaMisExpedientes,
    crearExpediente,
    actualizarExpediente,
    borrarExpediente,
    buscarExpediente,
    registroView,
    loginView
    )

urlpatterns = [
    path('app/',vistaApp.as_view(), name='dashboard' ),
    path('app/mis-expedientes/',vistaMisExpedientes.as_view(), name='mis_expedientes' ),
    path('app/expediente/pre_carga/',crearExpediente.as_view(), name='pre_carga' ),
    path('app/expediente/actualizar_pre_carga/<int:pk>/',actualizarExpediente.as_view(), name='actualizar_pre_carga' ),
    path('app/expediente/borrar/<int:pk>/',borrarExpediente.as_view(), name='borrar_expediente' ),
    path('app/expediente/buscar/',buscarExpediente.as_view(), name='buscar' ),
    path('app/expediente/<int:pk>/',vistaExpediente.as_view(), name='expediente' ),

    path('app/registro/',registroView.as_view(),name='user_registro'),
    # path('usuario/login/', LoginView.as_view(template_name='adminlte/usuario/login.html'), name="user_login"),
    path('app/login/',loginView.as_view(),name='user_login'),
]

juzgados/urls.py
from django.urls import path

from .views import (
    listaJuzgados,
    homeJuzgado,
    crearExpediente,
    actualizarExpediente,
    crearActualizacion,
    actualizarActualizacion,
    borrarActualizacion,
    loginView
    )

urlpatterns = [
    path('juzgado/',homeJuzgado.as_view(), name='juzgado' ),
    path('juzgado/lista/',listaJuzgados.as_view(), name='lista_juzgados' ),
    # Expediente
    path('juzgado/expediente/nuevo/',crearExpediente.as_view(), name='nuevo_expediente' ),
    path('juzgado/expediente/<int:pk>/',actualizarExpediente.as_view(), name='CRUD_expediente' ),
    # Actualizacion
    path('juzgado/nueva-actualizacion/<int:pk>/',crearActualizacion.as_view(), name='nueva_actualizacion' ),
    path('juzgado/actualizacion/<int:id_Act>/<int:id_Exp>/',actualizarActualizacion.as_view(), name='actualizacion' ),
    path('juzgado/actualizacion/borrar/<int:pk>/',borrarActualizacion.as_view(), name='borrar_actualizacion' ),
    # Usuario
    path('juzgado/login/',loginView.as_view(),name='juzgado_login'),
]

juzgadosonline/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from django.shortcuts import render

# def index(request):
# 	return render(request, 'home/index.html')

urlpatterns = [
    # path('avatar/', include('avatar.urls')),
    # path('', index(), name='index'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('select2/', include('django_select2.urls')),
    path('', include('expedientes.urls')),
    path('', include('juzgados.urls')),
    path('', include('extractor.urls')),
]

juzgados/models/ciudad.py
from django.db import models
from django.utils import timezone
from .provincia import Provincia


class Ciudad(models.Model):
   nombre = models.CharField(max_length=50)
   provincia = models.ForeignKey(Provincia, null=True, on_delete=models.CASCADE)
      
   def __str__(self):
      return self.nombre

expedientes/forms/actualizacion.py
from django import forms
from expedientes.models import Actualizacion


class ActualizacionForm(forms.ModelForm):
     class Meta():
         model = Actualizacion
         fields = ('expediente','tipo','contenido','fecha_creado','fecha_publicado','autor')

expedientes/forms/usuario.py
from django import forms
from django_select2.forms import Select2MultipleWidget, ModelSelect2Widget
from django.contrib.auth.models import User
from expedientes.models import Abogado


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')

class AbogadoForm(forms.ModelForm):
     class Meta():
         model = Abogado
         fields = ('avatar','nombre','apellido')

expedientes/views/buscar.py
from django.shortcuts import render
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
from expedientes.forms import buscarExpedienteForm
from expedientes.models import Expediente
from juzgados.services import juzgadoService

class buscarExpediente(LoginRequiredMixin, View):
   login_url = 'user_login'
   redirect_field_name = 'redirect_to'
   
   def get(self, request):
      form = buscarExpedienteForm()
      return render(request, "adminlte/buscar.html", {'form': form})

   def post(self, request):
      form = buscarExpedienteForm(request.POST)
      expedientes = []
      if form.is_valid():
            juzgado = self.request.POST.get('juzgado')
            numero = self.request.POST.get('numero')
            J = juzgadoService()
            expedientes = J.buscarExpediente(juzgado, numero)
      return render(request, "adminlte/buscar.html", {'form': form, 'expedientes':expedientes})   

expedientes/views/expediente.py
import datetime
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.views.generic import View, DetailView
from django.views.generic.base import TemplateView
from django.views.generic.edit import UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

from expedientes.services import expedienteDatoService

class vistaExpediente(LoginRequiredMixin, View):
   login_url = 'user_login'
   redirect_field_name = 'redirect_to'

   def get(self, request, pk):
      E = expedienteDatoService(request.user, pk)
      contexto = {
         'expediente':E.expediente,
         'ultimaActualizacion':E.ultimaActualizacion,
         'suscripto':E.subcripto,
         'actualizaciones': E.actualizaciones,
         'fechas':E.fechas,
         'caducidadad':E.caducidadad
         }
      return render(request, "adminlte/expediente.html", contexto)

   def post(self, request, pk):
      E = expedienteDatoService(request.user, pk)
      E.suscripcion()
      contexto = {
         'expediente':E.expediente,
         'ultimaActualizacion':E.ultimaActualizacion,
         'suscripto':E.subcripto,
         'actualizaciones': E.actualizaciones,
         'fechas':E.fechas,
         'caducidadad':E.caducidadad
         }
      return render(request, "adminlte/expediente.html", contexto) 

expedientes/views/misExpedientes.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import View,FormView
from django.views.generic.edit import (
   CreateView,
   UpdateView,
   DeleteView
)
from django.contrib.auth.mixins import LoginRequiredMixin
from expedientes.forms import SubsAgregarForm
from expedientes.services import MisExpediente
from expedientes.models import Expediente


class vistaMisExpedientes(LoginRequiredMixin, View):
   login_url = 'user_login'
   redirect_field_name = 'redirect_to'
   
   def get(self, request):
      expedientes = MisExpediente(request.user)
      return render(request, "adminlte/mis-expedientes.html", {
         'suscriptos':expedientes.suscriptos(),
         'creados':expedientes.creados()
         })


class crearExpediente(LoginRequiredMixin, View):
   login_url = 'user_login'
   redirect_field_name = 'redirect_to'
   
   def get(self, request):
      form = SubsAgregarForm()
      return render(request, "adminlte/expedientePreCarga.html", {'form': form})

   def post(self, request):
      form = SubsAgregarForm(request.POST)

      if form.is_valid():
            juzgado = self.request.POST.get('juzgado')
            numero = self.request.POST.get('numero')
            expediente = MisExpediente(request.user)
            expediente.preCargaCrear(juzgado, numero)
            return HttpResponseRedirect('/app/mis-expedientes/')
      return render(request, "adminlte/expedientePreCarga.html", {'form': form})      
         

class actualizarExpediente(LoginRequiredMixin, View):
   login_url = 'user_login'
   redirect_field_name = 'redirect_to'

   def get(self, request, pk):
      expedientes = MisExpediente(request.user)
      expediente = expedientes.getExpediente(pk)
      form = SubsAgregarForm(
         initial={
            "provincia": expediente.juzgado.ciudad.provincia,
            "ciudad": expediente.juzgado.ciudad,
            "juzgado": expediente.juzgado,
            "numero": expediente.numero,
            })
      
      return render(request, "adminlte/expedientePreCarga.html", {
         'form': form,
         'expediente': expediente
         })

   def post(self, request, pk):
      form = SubsAgregarForm(request.POST)

      if form.is_valid():
            juzgado = self.request.POST.get('juzgado')
            numero = self.request.POST.get('numero')
            expedientes = MisExpediente(request.user)
            expedientes.preCargaActualizar(pk, juzgado, numero)
            expediente = expedientes.getExpediente(pk)
            return HttpResponseRedirect('/app/mis-expedientes/')
      return render(request, "adminlte/expedientePreCarga.html", {
         'form': form,
         'expediente': expediente
         })


class borrarExpediente(LoginRequiredMixin, DeleteView):
   login_url = 'user_login'
   redirect_field_name = 'redirect_to'
   model = Expediente
   success_url = reverse_lazy('mis_expedientes')
   template_name = 'adminlte/borrar-expediente.html'

expedientes/views/usuario.py
from django.shortcuts import render
from expedientes.forms import AbogadoForm, UserForm
from django.views.generic import View, FormView
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required


class loginView(View):
   
   def post(self, request):
      form = AuthenticationForm(data=request.POST)
      username = request.POST.get('username')
      password = request.POST.get('password')
      if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                print(user)
                login(self.request, user)
                return HttpResponseRedirect('/app/')
            else:
                print('User not found')
      else:
            # If there were errors, we render the form with these
            # errors
            return render(request, 'adminlte/usuario/login.html', {'msg':'Credenciales Incorrectas'})
       
   
   def get(self, request):
      return render(request, 'adminlte/usuario/login.html', {})

class registroView(View):
   
   def post(self, request):    
      user_form = UserForm(data=request.POST)
      perfil_form = AbogadoForm(request.POST)
      if user_form.is_valid() and perfil_form.is_valid():
         user = user_form.save()
         user.set_password(user.password)
         user.save()
         # perfil = perfil_form.save()
         # perfil = perfil_form.save(commit=False)
         # perfil.usuario = user
         # # perfil.avatar = request.ger.
         # # if 'avatar' in request.FILES:
         # #    print('found it')
         # #    perfil.avatar = request.FILES['avatar']
         # perfil.save()

         return HttpResponseRedirect('/app/')
      else:
         user_form = UserForm()
         return render(request,'adminlte/usuario/register.html',{'user_form':user_form})


   def get(self, request):
      user_form = UserForm()
      perfil_form = AbogadoForm()
      return render(request,'adminlte/usuario/register.html',{})
      # return render(request,'adminlte/usuario/register.html',
      #                      {'user_form':user_form,
      #                      'perfil_form':perfil_form})      

juzgados/views/actualizacion.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import View
from django.views.generic.edit import (
   CreateView,
   UpdateView,
   DeleteView
)
from juzgados.forms import actualizacionForm
from juzgados.services import juzgadoService
from expedientes.services import expedienteService, actualizacionService
from expedientes.models import Expediente, Actualizacion
from juzgados.models import Delegado


class crearActualizacion(View):
   
   def get(self, request, pk):
      expediente = Expediente.objects.get(pk=pk)
      return render(request, "juzgado/juzgado-CRUD_actualizacion.html", {'expediente':expediente})

   def post(self, request, pk):
      form = actualizacionForm(request.POST)
      # print(self.request.POST.get('tipo'))
      # print(self.request.POST.get('contenido'))
      if form.is_valid():
         expediente = Expediente.objects.get(pk=pk)
         A = actualizacionService(request.user, expediente)
         A.agregar(self.request.POST.get('contenido'), self.request.POST.get('tipo'))
         return redirect('CRUD_expediente', pk=expediente.pk)
         # return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
      return render(request, "juzgado/juzgado-CRUD_actualizacion.html", {})      
         

class actualizarActualizacion(View):
   
   def get(self, request, id_Act, id_Exp):
      expediente = Expediente.objects.get(pk=id_Exp)
      actualizacion = Actualizacion.objects.get(pk=id_Act)
      return render(request, "juzgado/juzgado-CRUD_actualizacion.html", {
         'expediente': expediente,
         'actualizacion':actualizacion
         })

   def post(self, request, id_Act, id_Exp):
      form = actualizacionForm(request.POST)
      if form.is_valid():
         expediente = Expediente.objects.get(pk=id_Exp)
         actualizacion = actualizacionService(request.user, expediente)
         actualizacion.actualizar(
            id_Act,
            self.request.POST.get('contenido'),
            self.request.POST.get('tipo')
            )
         return redirect('CRUD_expediente', pk=expediente.pk)
      return render(request, "juzgado/juzgado-CRUD_actualizacion.html", {})


class borrarActualizacion(DeleteView):
   model = Actualizacion
   success_url = reverse_lazy('juzgado')
   template_name = ''    

juzgados/views/expediente.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.generic import View

from juzgados.forms import expedienteForm
from juzgados.services import juzgadoService
from expedientes.services import expedienteService, actualizacionesService
from expedientes.models import Expediente, Actualizacion
from juzgados.models import Delegado

class crearExpediente(View):
   
   def get(self, request):
      
      return render(request, "juzgado/juzgado-CRUD_expediente.html", {})

   def post(self, request):
      form = expedienteForm(request.POST)

      if form.is_valid():
            delegado = Delegado.objects.get(usuario=request.user)
            
            numero = self.request.POST.get('numero')
            actor = self.request.POST.get('actor')
            demandado = self.request.POST.get('demandado')
            causa = self.request.POST.get('causa')
            
            expediente = expedienteService(delegado.usuario, delegado.juzgado)
            expediente.agregar(numero, actor, demandado, causa)
            return HttpResponseRedirect('/juzgado/')
      return render(request, "juzgado/juzgado-CRUD_expediente.html", {})      
         

class actualizarExpediente(View):
   
   def get(self, request, pk):
      expediente = Expediente.objects.get(pk=pk)
      A = actualizacionesService(pk)
      # actualizaciones = Actualizacion.objects.filter(expediente=expediente)
      
      return render(request, "juzgado/juzgado-CRUD_expediente.html", {
         'expediente': expediente,
         'actualizaciones':A.actualizaciones
         })

   def post(self, request, pk):
      form = expedienteForm(request.POST)

      if form.is_valid():
            delegado = Delegado.objects.get(usuario=request.user)
            
            numero = self.request.POST.get('numero')
            actor = self.request.POST.get('actor')
            demandado = self.request.POST.get('demandado')
            causa = self.request.POST.get('causa')
            
            expediente = expedienteService(delegado.usuario, delegado.juzgado)
            expediente.actualizar(numero, actor, demandado, causa)
            return HttpResponseRedirect('/juzgado/')
      return render(request, "juzgado/juzgado-CRUD_expediente.html", {})         

juzgados/views/index.py
from django.shortcuts import render
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect
from juzgados.services import juzgadoService
from juzgados.models import Delegado

class homeJuzgado(LoginRequiredMixin, View):
   login_url = 'juzgado_login'
   redirect_field_name = 'redirect_to'
   
   def get(self, request):
      try:
         expedientes = juzgadoService()
         delegado = Delegado.objects.get(usuario=request.user)
         return render(request, "juzgado/juzgado-expedientes.html", {
         'expedientes':expedientes.getAllExpediente(delegado.juzgado.id),
         'creados':expedientes.getExpedienteAutor(delegado.juzgado.id, delegado.usuario.id)
         })
      except ObjectDoesNotExist:
         return HttpResponseRedirect('/app/')
      

templates/adminlte/actualizar-expediente.html
{% extends 'adminlte/base.html' %}

{% block content %}
<!-- Default box -->
<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">Nuevo Expediente</h3>

    </div>
    <div class="box-body">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Modificar" />
        </form>
    </div>
    <!-- /.box-body -->
    <div class="box-footer">
        <a class="btn btn-primary" href="{% url 'mis_expedientes' %}" role="button">
            <i class="fa fa-arrow-left"></i>
        </a>

        <div class="box-tools pull-right">

            <button type="button" class="btn btn-default" data-toggle="modal" data-target="#modal-borrar">
                <i class="fa fa-trash"></i>
            </button>
            <!-- Modal Borrar -->
            <div class="modal fade" id="modal-borrar">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title">Borrar Expediente {{ object.numero }}</h4>
                        </div>
                        <div class="modal-body">
                            <strong>¿Estás seguro que deseas borrar el expediente</strong> <br>
                            "{{ object }}"
                            <strong>?</strong>
                        </div>
                        <div class="modal-footer">

                            <form action="{% url 'borrar_expediente' pk=object.id %}" method="post">
                                {% csrf_token %}
                                <button class="btn btn-primary" type="submit">
                                    Borrar
                                </button>
                            </form>
                        </div>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
        </div>
    </div>
    <!-- /.box-footer-->
</div>
<!-- /.box -->
{% endblock %}

templates/adminlte/base.html
{% load static %}<!DOCTYPE html>
<html>
<head>
    {% block title_outer %}
        <title>{% block title %}{{ site.name }}{% endblock %}</title>
    {% endblock %}

    {% block meta %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-COMPATIBLE" content="IE=edge">
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    {% endblock %}

    {% block stylesheets %}
        {% include 'adminlte/lib/_styles.html' %}
    {% endblock %}

    {% block extra_head %}
        {{ form.media.css }}
    {% endblock %}
</head>
<body class="hold-transition skin-blue sidebar-mini {% block body_class %}{% block bodyclass %}{% endblock %}{% endblock %}">

{% block body %}
    <div class="wrapper">
        {% block nav_header %}
            {% include 'adminlte/lib/_main_header.html' %}
        {% endblock %}

        {% block nav_sidebar %}
            {% include 'adminlte/lib/_main_sidebar.html' %}
        {% endblock %}

        {% block content_wrapper %}
        <div class="content-wrapper">
            {% block content_header %}
                <section class="content-header">
                    {% block no_heading %}
                        <h1>
                            {% block page_name %}{% endblock %}
                            <div class="header-actions">
                                {% block page_actions %}{% endblock %}
                            </div>
                            {% block no_description %}
                            <small>{% block page_description %}{% endblock %}</small>
                            {% endblock %}
                        </h1>
                        {% block breadcrumbs %}
                            {# Breadcrumb implementation left to developers #}
                        {% endblock %}
                    {% endblock no_heading %}
                </section>
            {% endblock %}

            {% block content_outer %}
            <section class="content">
                {% block messages %}
                    {% include 'adminlte/lib/_messages.html' %}
                {% endblock %}

                {% block content_block_wrap %}
                    {% block content %}{% endblock %}
                {% endblock %}
            </section>
            {% endblock %}

        </div>
        {% endblock content_wrapper %}

        {% block nav_footer %}
            {% include 'adminlte/lib/_main_footer.html' %}
        {% endblock %}

    </div>
{% endblock body %}

{% block javascript %}
    {% include 'adminlte/lib/_scripts.html' %}
    {{ form.media.js }}
{% endblock %}

<!-- <script>
        $("#id_provincia").select2({
        dropdownAutoWidth : true
        });
</script> -->

{% block extra_foot %}{% endblock %}
</body>
</html>

templates/adminlte/borrar-expediente.html
{% extends 'adminlte/base.html' %}

{% block content %}
    <!-- Default box -->
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Borrar Expediente</h3>
             
        </div>
        <div class="box-body">
            <form method="post">{% csrf_token %}
                ¿Estás seguro que deseas borrar el expediente "{{ object }}"?
                <input type="submit" value="Borrar" />
            </form>
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->
{% endblock %}

templates/adminlte/buscar.html
{% extends 'adminlte/base.html' %}

{% block content %}
<!-- Default box -->
<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">Buscar Expediente</h3>
    </div>
    <div class="box-body">
 
        <form method="POST" action=".">
            {% csrf_token %}

            <div class="form-row">
                <div class="form-group col-md-6">
                    <label class="col-sm-2 col-form-label">{{form.provincia.label_tag}}</label>
                    <div class="col-sm-10">
                        {{form.provincia}}
                    </div>
                </div>
                <div class="form-group col-md-6">
                    <label class="col-sm-2 col-form-label">{{form.ciudad.label_tag}}</label>
                    <div class="col-sm-10">
                        {{form.ciudad}}
                    </div>
                </div>
            </div>
            <div class="form-group col-md-12">
                <label class="col-sm-2 col-form-label">{{form.juzgado.label_tag}}</label>
                <div class=" col-sm-10">
                    {{form.juzgado}}
                </div>
            </div>
            <div class="form-group col-md-12">
                <label class="col-sm-2 col-form-label">{{form.numero.label_tag}}</label>
                <div class=" col-sm-10">
                    {{form.numero}}
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-primary ">Buscar</button>
                </div>
            </div>
        </form>
    </div>
    <!-- /.box-body -->
</div>
<!-- /.box -->

    {% if expedientes %}
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">Resultado</h3>
          </div>
          <!-- /.box-header -->
          <div class="box-body">
            <table id="suscriptos" class="table table-bordered table-hover">
              <thead>
                <tr>
                  <th>Expediente</th>
                  <th>Juzgado</th>
                  <th>Fecha</th>
                  <th>...</th>
                </tr>
              </thead>
              <tbody>
                {% for expediente in expedientes %}
                <tr>
                  <td>{{ expediente.numero }}</td>
                  <td>{{ expediente.juzgado }}</td>
                  <td>{{ expediente.ultimaAct }} </td>
                  <td>
                    <a class="btn btn-primary" href="{% url 'expediente' pk=expediente.id %}" role="button">
                        <i class="fa fa-arrow-right"></i>
                    </a>                  
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
          <!-- /.box-body -->
        </div>
        <!-- /.box -->
    {% else %}
    <!-- <div class="alert alert-info alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <h4><i class="icon fa fa-info"></i> Sin resultados!</h4>
        No se encontraron expedietes.
    </div> -->
    {% endif %}

{% endblock %}

templates/adminlte/example.html
{% extends 'adminlte/base.html' %}

{% block content %}
    <!-- Default box -->
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Title</h3>

            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                        title="Collapse">
                    <i class="fa fa-minus"></i></button>
                <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip"
                        title="Remove">
                    <i class="fa fa-times"></i></button>
            </div>
        </div>
        <div class="box-body">
            Start creating your amazing application!
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            Footer
        </div>
        <!-- /.box-footer-->
    </div>
    <!-- /.box -->
{% endblock %}

templates/adminlte/expedientePreCarga.html
{% extends 'adminlte/base.html' %}

{% block content %}
<!-- Default box -->
<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">Nuevo Expediente</h3>
    </div>
    <div class="box-body">
 
        <form method="POST" action=".">
            {% csrf_token %}

            <div class="form-row">
                <div class="form-group col-md-6">
                    <label class="col-sm-2 col-form-label">{{form.provincia.label_tag}}</label>
                    <div class="col-sm-10">
                        {{form.provincia}}
                    </div>
                </div>
                <div class="form-group col-md-6">
                    <label class="col-sm-2 col-form-label">{{form.ciudad.label_tag}}</label>
                    <div class="col-sm-10">
                        {{form.ciudad}}
                    </div>
                </div>
            </div>
            <div class="form-group col-md-12">
                <label class="col-sm-2 col-form-label">{{form.juzgado.label_tag}}</label>
                <div class=" col-sm-10">
                    {{form.juzgado}}
                </div>
            </div>
            <div class="form-group col-md-12">
                <label class="col-sm-2 col-form-label">{{form.numero.label_tag}}</label>
                <div class=" col-sm-10">
                    {{form.numero}}
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-primary ">Publicar</button>
                </div>
            </div>
        </form>
    </div>
    <!-- /.box-body -->
    <div class="box-footer">
        <a class="btn btn-primary" href="{% url 'mis_expedientes' %}" role="button">
            <i class="fa fa-arrow-left"></i>
        </a>
        
        {% if expediente %}
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-default" data-toggle="modal" data-target="#modal-borrar">
                <i class="fa fa-trash"></i>
            </button>
            <!-- Modal Borrar -->
            <div class="modal fade" id="modal-borrar">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title">Borrar Expediente {{ expediente.numero }}</h4>
                        </div>
                        <div class="modal-body">
                            <strong>¿Estás seguro que deseas borrar el expediente</strong> <br>
                            "{{ expediente }}"
                            <strong>?</strong>
                        </div>
                        <div class="modal-footer">

                            <form action="{% url 'borrar_expediente' pk=expediente.id %}" method="post">
                                {% csrf_token %}
                                <button class="btn btn-primary" type="submit">
                                    Borrar
                                </button>
                            </form>
                        </div>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
        </div>
        {% endif %}
    </div>
    <!-- /.box-footer-->
</div>
<!-- /.box -->

{% endblock %}